### ISSUE TITLE
post error during camera opening

### ISSUE THREAD

**Issue by Vinter7** [remibert/pycameresp#8]
Hello, I've installed the firm for esp32cam, when I try to do this:

```py
# connect wifi
camera.init()

res = urequests.post(theUrl,json=data).json()
print(res)

camera.deinit()
```

I get the error: `OSError: [Errno 12] ENOMEM`

If I run `camera.deinit()`  before post request, it will be ok.

So I guess the error is due to camera opening.

**Comment by remibert** [comment]
Hello, 

if you receive the ENOMEM message, it means that Micropython didn't have enough memory to allocate the request. If the request is an image, you should try adjusting the resolution or quality to reduce the required amount of memory. Another parameter to consider is that if this message occurs after a few minutes of usage, it may be due to memory fragmentation. In that case, you need to periodically call the garbage collector to eliminate this issue. Please note that I don't use urequests for streaming in pycamerep because it will inevitably trigger reallocation of the image in memory. Instead, since I handle the HTTP protocol layer, I send the image directly, but you need to add the necessary HTTP headers and footers.
